default: &default
  call_platform_host: '<%= ENV.fetch("CALL_PLATFORM_HOST", "https://api.somleng.org") %>'
  call_platform_username: '<%= ENV.fetch("CALL_PLATFORM_USERNAME", "services") %>'

production: &production
  <<: *default
  region_data: '<%= ENV.fetch("REGION_DATA") %>'
  stub_regions: false
  sentry_dsn: "<%= app_settings.credentials.fetch('sentry_dsn') %>"
  queue_url: '<%= ENV.fetch("QUEUE_URL") %>'
  call_platform_password: "<%= ENV.fetch('CALL_PLATFORM_PASSWORD') %>"

staging:
  <<: *production
  call_platform_host: '<%= ENV.fetch("CALL_PLATFORM_HOST", "https://api-staging.somleng.org") %>'

development: &development
  <<: *default
  region_data: '<%= ENV.fetch("REGION_DATA", "{}") %>'
  stub_regions: true
  queue_url: '<%= ENV.fetch("QUEUE_URL", "https://sqs.us-east-1.amazonaws.com/123456789/queue") %>'
  call_platform_password: "<%= ENV.fetch('CALL_PLATFORM_PASSWORD', 'password') %>"

test:
  <<: *development
