default: &default
  region_data: '<%= ENV.fetch("REGION_DATA", "{}") %>'
  stub_regions: false

production: &production
  <<: *default
  sentry_dsn: "<%= app_settings.credentials.fetch('sentry_dsn') %>"
  queue_url: '<%= ENV.fetch("QUEUE_URL") %>'

staging:
  <<: *production

development: &development
  <<: *default
  stub_regions: true
  queue_url: '<%= ENV.fetch("QUEUE_URL", "https://sqs.us-east-1.amazonaws.com/123456789/queue") %>'

test:
  <<: *development
