# This docker-compose configuration is intended to be used for integration testing only.
#
# Note:
# Assumes postgres is running on the host machine.
# Postgres is not included in this docker-compose configuration
# because of the complexity of adding code to wait for postgres to start.

version: "3.9"
volumes:
  workspace:
  opensips_fifo:

services:
  gateway-bootstrap:
    build:
      context: components/gateway
      target: bootstrap
    image: gateway:bootstrap
    platform: linux/amd64
    environment:
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD:
      DATABASE_NAME:
      DATABASE_HOST: "host.docker.internal"
      DATABASE_PORT: 5432
    extra_hosts:
      - "host.docker.internal:host-gateway"

  public_gateway:
    build:
      context: components/gateway
      target: public_gateway
    image: public_gateway:latest
    platform: linux/amd64
    environment:
      DATABASE_URL: "postgres://postgres:@host.docker.internal:5432/opensips_public_gateway_test"
      FIFO_NAME: /opensips/fifo/public_gateway
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD-SHELL", "nc -z -w 5 $$(hostname -i) 5060"]
      interval: 10s
      timeout: 5s
      retries: 10
    expose:
      - "5060/udp"
      - "5080/udp"
    volumes:
      - opensips_fifo:/opensips/fifo

  client_gateway:
    build:
      context: components/gateway
      target: client_gateway
    image: client_gateway:latest
    platform: linux/amd64
    environment:
      DATABASE_URL: "postgres://postgres:@host.docker.internal:5432/opensips_client_gateway_test"
      FIFO_NAME: /opensips/fifo/client_gateway
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD-SHELL", "nc -z -w 5 $$(hostname -i) 5060"]
      interval: 10s
      timeout: 5s
      retries: 10
    expose:
      - "5060/udp"
    volumes:
      - opensips_fifo:/opensips/fifo

  media_proxy:
    build:
      context: components/media_proxy
    image: media_proxy:latest
    platform: linux/amd64
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD-SHELL", "nc -z -w 5 $$(hostname -i) 2224"]
      interval: 10s
      timeout: 5s
      retries: 10
    expose:
      - "2223/udp"

  freeswitch:
    build:
      context: components/freeswitch
    image: freeswitch:latest
    platform: linux/amd64
    environment:
      FS_EXTERNAL_RTP_IP: "13.250.230.15"
      FS_ALTERNATIVE_RTP_IP: "18.141.245.230"
    expose:
      - "5060/udp"
      - "5222/tcp"
      - "5080/udp"
      - "8021/tcp"
    healthcheck:
      test:
        ["CMD-SHELL", "fs_cli -p secret -x 'rayo status' | rayo_status_parser"]
      interval: 10s
      timeout: 5s
      retries: 10

  switch-app:
    build:
      context: components/app
    image: switch-app:latest
    platform: linux/amd64
    environment:
      AHN_CORE_HOST: freeswitch
      CALL_PLATFORM_STUB_RESPONSES: "true"
      AHN_CORE_HTTP_PORT: "8080"
      AWS_DEFAULT_REGION: "ap-southeast-1"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --server-response --spider --quiet http://localhost:8080/health_checks 2>&1 | grep '200 OK' > /dev/null",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    expose:
      - "8080/tcp"

  testing:
    build:
      context: components/testing
    image: testing:latest
    command: sipp -sf /scenarios/uas.xml -trace_msg
    environment:
      DATABASE_HOST: host.docker.internal
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      FIFO_DIR: /opensips/fifo
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - workspace:/workspace
      - opensips_fifo:/opensips/fifo
