version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  opensips-bootstrap-db:
    build:
      context: docker/opensips
      target: bootstrap
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/opensips"
    depends_on:
      - db

  opensips-bootstrap-db-data:
    build:
      context: docker/opensips
      target: bootstrap
    environment:
      PGPASSWORD: "password"
    command: "psql --host=db --username=postgres --dbname opensips --command=\"INSERT INTO load_balancer (group_id, dst_uri, resources, probe_mode) VALUES('1', 'sip:freeswitch:5060', 'gw=fs://:secret@freeswitch:8021', 2), ('1', 'sip:freeswitch:5080', 'gw=fs://:secret@freeswitch:8021', 2) \""
    depends_on:
      - db

  somleng-switch:
    build:
      context: .
    environment:
      AHN_CORE_HOST: freeswitch
      AHN_CORE_HTTP_PORT: 8080
      APP_ENV: test_integration
    depends_on:
      - freeswitch
    healthcheck:
      test: ["CMD-SHELL", "wget --server-response --spider --quiet http://localhost:8080/health_checks 2>&1 | grep '200 OK' > /dev/null"]
      interval: 10s
      timeout: 5s
      retries: 10

  freeswitch:
    build:
      context: docker/freeswitch
    healthcheck:
      test: ["CMD-SHELL", "nc -z -w 5 localhost 5222"]
      interval: 10s
      timeout: 5s
      retries: 10

  opensips:
    build:
      context: docker/opensips
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/opensips"
      SIP_ADVERTISED_IP: opensips
    ports:
      - "5060:5060/udp"
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "nc -z -w 5 localhost 5222"]
      interval: 10s
      timeout: 5s
      retries: 10
