# This docker-compose configuration is intended to be used for integration testing only.
#
# Usage:
#
# $ docker-compose run opensips-bootstrap-db
# $ docker-compose run opensips-bootstrap-db-data
# $ docker-compose up opensips freeswitch somleng-switch
#
# Note:
# Assumes postgres is running on the host machine.
# Postgres is not included in this docker-compose configuration
# because of the complexity of adding code to wait for postgres to start.

version: "3.9"
volumes:
  workspace:
  opensips_fifo:

services:
  opensips-bootstrap-db:
    build:
      context: docker/opensips
      target: bootstrap
    image: opensips:bootstrap
    environment:
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD:
      DATABASE_HOST: "host.docker.internal"
      DATABASE_PORT: 5432
      DATABASE_NAME: "opensips"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  opensips:
    build:
      context: docker/opensips
    image: opensips:latest
    environment:
      DATABASE_URL: "postgres://postgres:@host.docker.internal:5432/opensips"
      FIFO_NAME: /opensips/fifo/opensips_fifo
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD-SHELL", "nc -z -w 5 localhost 5060"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - opensips_fifo:/opensips/fifo

  freeswitch:
    build:
      context: docker/freeswitch
    image: freeswitch:latest
    environment:
      FS_EXTERNAL_RTP_IP: "13.250.230.15"
      FS_ALTERNATIVE_RTP_IP: "18.141.245.230"
    healthcheck:
      test:
        ["CMD-SHELL", "fs_cli -p secret -x 'rayo status' | rayo_status_parser"]
      interval: 10s
      timeout: 5s
      retries: 10

  somleng-switch:
    build:
      context: .
    image: somleng-switch:latest
    environment:
      AHN_CORE_HOST: freeswitch
      CALL_PLATFORM_STUB_RESPONSES: "true"
      AHN_CORE_HTTP_PORT: "8080"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --server-response --spider --quiet http://localhost:8080/health_checks 2>&1 | grep '200 OK' > /dev/null",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  testing:
    build:
      context: docker/testing
    image: testing:latest
    command: sipp -sn uas -trace_msg
    environment:
      OPENSIPS_FIFO_NAME: /opensips/fifo/opensips_fifo
      DATABASE_URL: "postgres://postgres:@host.docker.internal:5432/opensips"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - workspace:/workspace
      - opensips_fifo:/opensips/fifo
