default: &default

production: &production
  <<: *default
  sentry_dsn: "<%= app_settings.credentials.fetch('sentry_dsn') %>"

staging:
  <<: *production

development: &development
  <<: *default
  stub_regions: true

test:
  <<: *development
