source "https://rubygems.org"

gem "adhearsion", github: "somleng/adhearsion"
gem "aws-sdk-lambda"
gem "aws-sdk-polly"
gem "blather", github: "adhearsion/blather", branch: "develop"
gem "faraday"
gem "http"
gem "okcomputer"
gem "phony"
gem "reel-rack", github: "samnang/reel-rack", branch: "switch_to_use_integer"
gem "sentry-ruby"
gem "sinatra"
gem "sinatra-contrib", require: false
gem "skylight"
gem "sucker_punch"
gem "tts_voices", github: "somleng/tts_voices"

group :development, :test do
  gem "rubocop"
  gem "rubocop-performance"
  gem "rubocop-rspec"
end

group :test do
  gem "rack-test"
  gem "rspec"
  gem "simplecov", require: false
  gem "simplecov-cobertura", require: false
  gem "twilio-ruby"
  gem "vcr"
  gem "webmock"
end
