# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem "aws-sdk-s3"
gem "ox" # XML parser. required by aws-sdk-s3

group :test do
  gem "rspec"
  gem "simplecov", require: false
  gem "simplecov-cobertura", require: false
end
