# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem "pg"

group :test do
  gem "activesupport"
  gem "pry"
  gem "rspec"
end
