# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem "aws-sdk-ec2"
gem "aws-sdk-ecs"
gem "aws-sdk-sqs"
gem "aws-sdk-ssm"
gem "base64"
gem "encrypted_credentials", github: "somleng/encrypted_credentials"
gem "faraday"
gem "ox" # XML parser. required by aws-sdk-s3
gem "pg"
gem "sentry-ruby"
gem "sequel"

group :development do
  gem "rake"
  gem "rubocop"
  gem "rubocop-rspec"
  gem "rubocop-performance"
  gem "rubocop-rails-omakase"
end

group :test do
  gem "pry"
  gem "rspec"
  gem "simplecov", require: false
  gem "simplecov-cobertura", require: false
  gem "webmock"
end
