name: Build
on: push

env:
  CI: true

jobs:
  # s3_mpeg_tests:
  #   uses: ./.github/workflows/s3_mpeg_tests.yml
  #   secrets: inherit

  # services_tests:
  #   uses: ./.github/workflows/services_tests.yml
  #   secrets: inherit

  # switch_tests:
  #   uses: ./.github/workflows/switch_tests.yml
  #   secrets: inherit

  # integration_tests:
  #   uses: ./.github/workflows/integration_tests.yml
  #   needs: [switch_tests, s3_mpeg_tests, services_tests]
  #   secrets: inherit

  set-build-matrix:
    name: Set Build Matrix
    # needs: integration_tests
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-build-matrix.outputs.matrix }}
      matrixLength: ${{ steps.set-build-matrix.outputs.matrixLength }}
    steps:
      - name: Set Build Matrix
        id: set-build-matrix
        run: |
          branchName=$(echo '${{ github.ref }}' | sed 's,refs/heads/,,g')
          matrixSource=$(cat << EOF
          [
            {
              "branch": "improve_ci",
              "environment": "staging",
              "friendly_image_tag": "beta",
              "image_tag": "stag-${{ github.sha }}"
            },
            {
              "branch": "master",
              "environment": "production",
              "friendly_image_tag": "latest",
              "image_tag": "prod-${{ github.sha }}"
            }
          ]
          EOF
          )

          matchedArray=$(echo "$matrixSource" | jq -c --arg branchName "$branchName" 'map(select(.branch==$branchName))')
          matrixLength=$(echo "$matchedArray" | jq 'length')
          matrix=$(echo "$matchedArray" | jq -c '.[0]')
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
          echo "matrixLength=$matrixLength" >> $GITHUB_OUTPUT

  build_switch:
    uses: ./.github/workflows/switch_build.yml
    needs: set-build-matrix
    if: needs.set-build-matrix.outputs.matrixLength > 0
    secrets: inherit
    with:
      build-matrix: ${{ needs.set-build-matrix.outputs.matrix }}

  # build_rating_engine:
  #   uses: ./.github/workflows/rating_engine_build.yml
  #   needs: integration_tests
  #   secrets: inherit

  deploy_switch:
    uses: ./.github/workflows/switch_deploy.yml
    needs: [build_switch, build_rating_engine]
    if: needs.set-build-matrix.outputs.matrixLength > 0
    secrets: inherit
    with:
      build-matrix: ${{ needs.set-build-matrix.outputs.matrix }}

  # deploy_rating_engine:
  #   uses: ./.github/workflows/rating_engine_deploy.yml
  #   needs: build_rating_engine
  #   secrets: inherit

  # build_opensips_scheduler:
  #   uses: ./.github/workflows/opensips_scheduler_build.yml
  #   needs: integration_tests
  #   secrets: inherit

  # deploy_s3_mpeg:
  #   uses: ./.github/workflows/s3_mpeg_deploy.yml
  #   needs: integration_tests
  #   secrets: inherit

  # deploy_services:
  #   uses: ./.github/workflows/services_deploy.yml
  #   needs: integration_tests
  #   secrets: inherit

  # deploy_public_gateway:
  #   uses: ./.github/workflows/public_gateway_deploy.yml
  #   needs: [build_opensips_scheduler]
  #   secrets: inherit

  # deploy_client_gateway:
  #   uses: ./.github/workflows/client_gateway_deploy.yml
  #   needs: [build_opensips_scheduler]
  #   secrets: inherit

  # deploy_media_proxy:
  #   uses: ./.github/workflows/media_proxy_deploy.yml
  #   needs: integration_tests
  #   secrets: inherit
