name: Build
on: push

env:
  CI: true

jobs:
  s3_mpeg:
    uses: ./.github/workflows/s3_mpeg.yml
    with:
      context: unit-tests
    secrets: inherit

  services:
    uses: ./.github/workflows/services.yml
    with:
      context: unit-tests
    secrets: inherit

  integration_tests:
    uses: ./.github/workflows/integration_tests.yml
    needs: [s3_mpeg, services]
    secrets: inherit

  deploy:
    uses: ./.github/workflows/s3_mpeg.yml
    with:
      context: deploy
    needs: [integration_tests]
    secrets: inherit
