name: S3 MPEG
on: workflow_call

env:
  CI: true
  REPOSITORY_NAME: s3-mpeg

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: components/s3_mpeg

    steps:
      - uses: FedericoCarboni/setup-ffmpeg@v3

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: components/s3_mpeg
          bundler-cache: true

      - name: Run Specs
        run: |
          bundle exec rspec

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
