on: workflow_call
name: Switch

env:
  CI: true
  APP_REPOSITORY_NAME: switch-app
  RATING_ENGINE_REPOSITORY_NAME: rating-engine
  WEBSERVER_REPOSITORY_NAME: switch-webserver
  FREESWITCH_REPOSITORY_NAME: freeswitch
  FREESWITCH_STATS_LOGGER_REPOSITORY_NAME: freeswitch-stats-logger
  FREESWITCH_EVENT_PROCESSOR_REPOSITORY_NAME: freeswitch-event-processor

jobs:
  set-deployment-matrix:
    name: Set Deployment Matrix
    runs-on: ubuntu-latest
    outputs:
      matrixLength: ${{ steps.set-deployment-matrix.outputs.matrixLength }}
      deployMatrix: ${{ steps.set-deployment-matrix.outputs.deployMatrix }}
    steps:
      - name: Set Deployment Matrix
        id: set-deployment-matrix
        run: |
          branchName=$(echo '${{ github.ref }}' | sed 's,refs/heads/,,g')
          matrixSource=$(cat << EOF
          [
            {
              "identifier": "switch-staging",
              "environment": "staging",
              "branch": "fix_switch_host_for_inbound_calls",
              "image_tag": "stag-${{ github.sha }}",
              "ecs_service": "switch-staging",
              "ecs_cluster": "somleng-switch-staging"
            },
            {
              "identifier": "switch",
              "environment": "production",
              "branch": "master",
              "image_tag": "prod-${{ github.sha }}",
              "ecs_service": "switch",
              "ecs_cluster": "somleng-switch"
            }
          ]
          EOF
          )
          matrix=$(echo $matrixSource | jq --arg branchName "$branchName" 'map(. | select((.branch==$branchName)) )')
          echo "matrixLength=$(echo $matrix | jq length)" >> $GITHUB_OUTPUT
          echo "deployMatrix={\"region\":[\"ap-southeast-1\",\"us-east-1\"],\"include\":$(echo $matrix)}" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - set-deployment-matrix

    strategy:
      matrix: ${{fromJSON(needs.set-deployment-matrix.outputs.deployMatrix)}}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600
          aws-region: ${{ matrix.region }}

      - name: Get current task definition
        run: |
          aws ecs describe-task-definition --task-definition "${{ matrix.identifier }}" --query 'taskDefinition' > task-definition.json

      - name: Prepare Webserver task definition
        id: render-nginx-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: nginx
          image: ${{ secrets.ECR_REGISTRY }}/${{ env.WEBSERVER_REPOSITORY_NAME }}:${{ matrix.image_tag }}

      - name: Prepare FreeSWITCH task definition
        id: render-freeswitch-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.render-nginx-task-def.outputs.task-definition }}
          container-name: freeswitch
          image: ${{ secrets.ECR_REGISTRY }}/${{ env.FREESWITCH_REPOSITORY_NAME }}:${{ matrix.image_tag }}

      - name: Prepare FreeSWITCH stats logger task definition
        id: render-freeswitch-stats-logger-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.render-freeswitch-task-def.outputs.task-definition }}
          container-name: freeswitch-stats-logger
          image: ${{ secrets.ECR_REGISTRY }}/${{ env.FREESWITCH_STATS_LOGGER_REPOSITORY_NAME }}:${{ matrix.image_tag }}

      - name: Prepare FreeSWITCH event processor task definition
        id: render-freeswitch-event-processor-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.render-freeswitch-stats-logger-task-def.outputs.task-definition }}
          container-name: freeswitch-event-processor
          image: ${{ secrets.ECR_REGISTRY }}/${{ env.FREESWITCH_EVENT_PROCESSOR_REPOSITORY_NAME }}:${{ matrix.image_tag }}

      - name: Prepare Rating Engine task definition
        id: render-rating-engine-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.render-freeswitch-event-processor-task-def.outputs.task-definition }}
          container-name: rating-engine
          image: ${{ secrets.ECR_REGISTRY }}/${{ env.RATING_ENGINE_REPOSITORY_NAME }}:${{ matrix.image_tag }}

      - name: Prepare App task definition
        id: render-app-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ steps.render-rating-engine-task-def.outputs.task-definition }}
          container-name: app
          image: ${{ secrets.ECR_REGISTRY }}/${{ env.APP_REPOSITORY_NAME }}:${{ matrix.image_tag }}

      - name: Deploy Switch
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-app-task-def.outputs.task-definition }}
          service: ${{ matrix.ecs_service }}
          cluster: ${{ matrix.ecs_cluster }}
          wait-for-service-stability: true

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - set-deployment-matrix
      - deploy

    strategy:
      matrix: ${{fromJson(needs.set-deployment-matrix.outputs.deployMatrix)}}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: somleng
          SENTRY_PROJECT: somleng-switch
        with:
          environment: ${{ matrix.environment }}
