ENV["SWITCH_GROUP"] = "service:somleng-switch"
ENV["FS_EVENT_SOCKET_PASSWORD_SSM_PARAMETER_NAME"] = "ssm-parameter-name-fs-event-socket-password"
ENV["FS_EVENT_SOCKET_PORT"] = "8021"
ENV["OPENSIPS_DB_NAME"] = "opensips_test"
ENV["SWITCH_PERMISSIONS_QUEUE_ARN"] = "arn:aws:sqs:us-east-2:123456789012:somleng-switch-permissions"
